package cloud.apposs.websocket.sample;

import cloud.apposs.websocket.WSSession;
import cloud.apposs.websocket.annotation.*;
import cloud.apposs.websocket.protocol.Metadata;
import cloud.apposs.websocket.sample.bean.AttachmentObject;
import cloud.apposs.websocket.sample.bean.ChatObject;
import cloud.apposs.websocket.sample.bean.ChatUsers;

import java.util.Map;
import java.util.UUID;

@ServerEndpoint("/socket.io")
public class SocketIOEndpoint {
    public static final String CMD_01 = "echo";

    @OnConnect
    public void onConnect(WSSession session) {
        System.out.println("user connected");
    }

    @OnCommand(CMD_01)
    public void onCommand01(WSSession session, String message) throws Exception {
        System.out.println("onCommand01 " + message);
        session.sendCommand(CMD_01, message + " from Server");
    }

    @OnCommand("chat")
    public void onCommand02(WSSession session, ChatObject message, String username) throws Exception {
        System.out.println("onCommand02 " + message.getUsername() + ": " + message.getMessage());
        session.sendCommand("chat", message.getUsername() + ": " + message.getMessage() + " from Server", "Another param");
    }

    @OnCommand("users")
    public void onCommand03(WSSession session, ChatUsers users) throws Exception {
        session.disconnect();
        System.out.println("onCommand03 " + users.getUsers());
    }

    @OnCommand("binary")
    public void onCommand04(WSSession session, byte[] data) throws Exception {
        session.disconnect();
        System.out.println("onCommand04 " + data.length);
    }

    @OnCommand("broadcast")
    public void onCommand05(WSSession session, ChatObject data) throws Exception {
        System.out.println("onCommand03");
        data.setMessage("from server0");
        // 分发在集群中所有连接的客户端
        Map<UUID, String> sessionList = session.getNamespace().getDistributedSessions();
        for (UUID sessionId : sessionList.keySet()) {
            if (sessionId.equals(session.getSessionId())) {
                continue;
            }
            ChatObject replyData = new ChatObject();
            replyData.setUsername(data.getUsername());
            replyData.setMessage("reply to " + sessionId);
            session.getDistributedSessionOperations(sessionId).sendCommand(CMD_01, replyData);
        }
        System.out.println(sessionList);
    }

    @OnCommand("wsrpc")
    public void onCommand06(WSSession session, Metadata metadata, ChatObject data) throws Exception {
        System.out.println("onCommand06: " + data.getUsername());
        // 直接调用客户端的命令，类似于RPC调用
        ChatObject replyData = new ChatObject();
        replyData.setUsername(data.getUsername());
        replyData.setMessage("reply to " + session.getSessionId());
        session.sendResponse(metadata.getCommandId(), replyData);
    }

    @OnCommand("attachment")
    public void onCommand07(WSSession session, AttachmentObject attachmentObject, String message) throws Exception {
        System.out.println("onAttachment, name: " + attachmentObject.getName() + ", content: " + new String(attachmentObject.getContent()));
        session.sendCommand("event_send02", "from server1");
    }

    @OnCommand("download")
    public void onCommand08(WSSession session, Metadata metadata) throws Exception {
        AttachmentObject attachment = new AttachmentObject();
        attachment.setName("test.txt");
        String content = "This is a test file.\nGenerated by WS 服务.";
        attachment.setContent(content.getBytes());
        attachment.setSize(attachment.getContent().length);
        session.sendResponse(metadata.getCommandId(), attachment);
    }

    @OnError
    public void onError(Throwable ex) {
        System.out.println("exp caught " + ex.getMessage());
        ex.printStackTrace();
    }

    @OnDisconnect
    public void onDisconnect(WSSession session) {
        System.err.println("disconnected");
    }
}
